#!/usr/bin/env bash
#
# CLI Installer - install OAuth creators as reusable shell commands.
# Usage: ./install-cli.sh [--uninstall]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="github-oauth-automator"
SNIPPET_DIR="${HOME}/.config/oauth-creator"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${CYAN}➤${NC} $1"; }
log_ok() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

normalize_shell() {
    local raw="${1:-}"
    raw="${raw##*/}"

    case "$raw" in
        bash|zsh|fish|sh)
            printf '%s\n' "$raw"
            ;;
        "")
            printf 'sh\n'
            ;;
        *)
            printf '%s\n' "$raw"
            ;;
    esac
}

detect_shell() {
    local shell_name=""

    if [[ -n "${SHELL:-}" ]]; then
        shell_name="$(normalize_shell "$SHELL")"
    fi

    if [[ -z "$shell_name" || "$shell_name" == "sh" ]]; then
        if command -v getent >/dev/null 2>&1; then
            shell_name="$(getent passwd "$USER" | awk -F: '{print $7}' | xargs basename 2>/dev/null || true)"
            shell_name="$(normalize_shell "$shell_name")"
        elif command -v dscl >/dev/null 2>&1; then
            shell_name="$(dscl . -read "/Users/$USER" UserShell 2>/dev/null | awk '{print $2}' | xargs basename 2>/dev/null || true)"
            shell_name="$(normalize_shell "$shell_name")"
        fi
    fi

    if [[ -z "$shell_name" || "$shell_name" == "sh" ]]; then
        if [[ -f "${HOME}/.zshrc" || -f "${HOME}/.zprofile" ]]; then
            shell_name="zsh"
        elif [[ -f "${HOME}/.config/fish/config.fish" ]]; then
            shell_name="fish"
        elif [[ -f "${HOME}/.bashrc" || -f "${HOME}/.bash_profile" ]]; then
            shell_name="bash"
        else
            shell_name="sh"
        fi
    fi

    printf '%s\n' "$shell_name"
}

get_user_bin_dir() {
    python3 - <<'PY'
import os
import site
print(os.path.join(site.USER_BASE, "bin"))
PY
}

get_tool_bin_dir() {
    if [[ -n "${UV_TOOL_BIN_DIR:-}" ]]; then
        printf '%s\n' "$UV_TOOL_BIN_DIR"
    else
        printf '%s\n' "${HOME}/.local/bin"
    fi
}

get_install_bin_dir() {
    local installer="$1"
    case "$installer" in
        uv|pipx)
            get_tool_bin_dir
            ;;
        pip)
            get_user_bin_dir
            ;;
        *)
            printf '%s\n' "${HOME}/.local/bin"
            ;;
    esac
}

pick_installer() {
    if command -v uv >/dev/null 2>&1; then
        printf 'uv\n'
    elif command -v pipx >/dev/null 2>&1; then
        printf 'pipx\n'
    elif command -v python3 >/dev/null 2>&1 && python3 -m pip --version >/dev/null 2>&1; then
        printf 'pip\n'
    else
        printf '\n'
    fi
}

install_package() {
    local installer="$1"

    log_info "Installing package with ${installer}..."

    case "$installer" in
        uv)
            uv tool install --editable "$SCRIPT_DIR" --force --quiet
            ;;
        pipx)
            pipx install --editable "$SCRIPT_DIR" --force
            ;;
        pip)
            python3 -m pip install --user --editable "$SCRIPT_DIR" --quiet
            ;;
        *)
            log_error "No supported installer found. Install uv, pipx, or python3 + pip."
            exit 1
            ;;
    esac

    log_ok "Package installed"
}

get_snippet_path() {
    local shell_name="$1"
    case "$shell_name" in
        fish)
            printf '%s/oauth-creator.fish\n' "$SNIPPET_DIR"
            ;;
        bash)
            printf '%s/oauth-creator.bash\n' "$SNIPPET_DIR"
            ;;
        *)
            printf '%s/oauth-creator.sh\n' "$SNIPPET_DIR"
            ;;
    esac
}

write_snippet() {
    local shell_name="$1"
    local bin_dir="$2"
    local snippet

    mkdir -p "$SNIPPET_DIR"
    snippet="$(get_snippet_path "$shell_name")"

    case "$shell_name" in
        fish)
            cat >"$snippet" <<EOF
#!/usr/bin/env fish
# Generated by install-cli.sh
if not contains "$bin_dir" \$PATH
    set -gx PATH "$bin_dir" \$PATH
end
alias create-oauth create-github-oauth
EOF
            ;;
        *)
            cat >"$snippet" <<EOF
#!/usr/bin/env sh
# Generated by install-cli.sh
case ":\$PATH:" in
    *:"$bin_dir":*) ;;
    *) export PATH="$bin_dir:\$PATH" ;;
esac
alias create-oauth='create-github-oauth'
EOF
            ;;
    esac

    chmod 755 "$snippet"
    printf '%s\n' "$snippet"
}

get_rc_file() {
    local shell_name="$1"

    case "$shell_name" in
        zsh)
            if [[ -f "${HOME}/.zshrc" ]]; then
                printf '%s/.zshrc\n' "$HOME"
            elif [[ -f "${HOME}/.zprofile" ]]; then
                printf '%s/.zprofile\n' "$HOME"
            else
                printf '%s/.zshrc\n' "$HOME"
            fi
            ;;
        fish)
            printf '%s/.config/fish/config.fish\n' "$HOME"
            ;;
        bash)
            if [[ -f "${HOME}/.bashrc" ]]; then
                printf '%s/.bashrc\n' "$HOME"
            elif [[ -f "${HOME}/.bash_profile" ]]; then
                printf '%s/.bash_profile\n' "$HOME"
            elif [[ -f "${HOME}/.profile" ]]; then
                printf '%s/.profile\n' "$HOME"
            else
                printf '%s/.bashrc\n' "$HOME"
            fi
            ;;
        sh)
            if [[ -f "${HOME}/.profile" ]]; then
                printf '%s/.profile\n' "$HOME"
            else
                printf '%s/.profile\n' "$HOME"
            fi
            ;;
        *)
            printf '\n'
            ;;
    esac
}

get_source_line() {
    local shell_name="$1"
    local snippet="$2"

    case "$shell_name" in
        fish)
            printf 'test -f "%s"; and source "%s"\n' "$snippet" "$snippet"
            ;;
        *)
            printf '[ -f "%s" ] && . "%s"\n' "$snippet" "$snippet"
            ;;
    esac
}

ensure_source_in_rc() {
    local shell_name="$1"
    local snippet="$2"
    local rc_file="$3"
    local source_line

    if [[ -z "$rc_file" ]]; then
        return 1
    fi

    mkdir -p "$(dirname "$rc_file")"
    touch "$rc_file"
    source_line="$(get_source_line "$shell_name" "$snippet")"

    if grep -Fq "$snippet" "$rc_file" 2>/dev/null; then
        log_warn "Shell config already sources $(basename "$snippet")"
        return 0
    fi

    {
        printf '\n'
        printf '# Added by OAuth CLI installer\n'
        printf '%s' "$source_line"
    } >>"$rc_file"

    log_ok "Added source line to $rc_file"
}

print_manual_guidance() {
    local shell_name="$1"
    local rc_file="$2"
    local snippet="$3"
    local bin_dir="$4"

    echo ""
    echo -e "${CYAN}Shell integration guidance${NC}"
    echo "  Detected shell: ${shell_name}"
    echo "  CLI bin dir:    ${bin_dir}"
    echo "  Snippet file:   ${snippet}"
    echo ""
    echo "Commands available after your shell reloads:"
    echo "  create-oauth"
    echo "  create-github-oauth"
    echo "  create-google-oauth"
    echo ""

    if [[ -n "$rc_file" ]]; then
        echo "If your shell config is unusual, add this line to ${rc_file}:"
        echo "  $(get_source_line "$shell_name" "$snippet")"
    else
        echo "Your shell is not one of bash, zsh, fish, or sh."
        echo "Add the generated snippet to your shell startup config manually."
    fi

    echo ""
    echo "You can apply it in the current shell now with:"
    case "$shell_name" in
        fish)
            echo "  source \"$snippet\""
            ;;
        *)
            echo "  . \"$snippet\""
            ;;
    esac
}

verify_installation() {
    local bin_dir="$1"
    local commands=(
        "${bin_dir}/create-github-oauth"
        "${bin_dir}/create-google-oauth"
    )
    local found=0

    log_info "Verifying installation..."

    for cmd in "${commands[@]}"; do
        if [[ -x "$cmd" ]]; then
            log_ok "$(basename "$cmd") is installed in $bin_dir"
            ((found+=1))
        else
            log_warn "$(basename "$cmd") was not found in $bin_dir"
        fi
    done

    if [[ "$found" -lt 2 ]]; then
        log_warn "The CLI was installed, but your shell may still be missing the bin dir in PATH."
        return 1
    fi

    return 0
}

uninstall_package() {
    local installer
    installer="$(pick_installer)"

    log_info "Uninstalling..."

    case "$installer" in
        uv)
            uv tool uninstall "$APP_NAME" >/dev/null 2>&1 || true
            ;;
        pipx)
            pipx uninstall "$APP_NAME" >/dev/null 2>&1 || true
            ;;
        pip)
            python3 -m pip uninstall "$APP_NAME" -y >/dev/null 2>&1 || true
            ;;
        *)
            log_warn "No supported installer found for automatic uninstall."
            ;;
    esac

    log_ok "Package uninstall attempted"
    echo "Shell snippet files in ${SNIPPET_DIR} were left in place."
    echo "Remove the source line from your shell config if you no longer want the shortcut."
}

main() {
    local uninstall=false
    local shell_name=""
    local installer=""
    local bin_dir=""
    local snippet=""
    local rc_file=""

    if [[ "${1:-}" == "--uninstall" ]]; then
        uninstall=true
    fi

    echo ""
    echo -e "${CYAN}╔═══════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║   OAuth CLI Installer                    ║${NC}"
    echo -e "${CYAN}╚═══════════════════════════════════════════╝${NC}"
    echo ""

    if [[ "$uninstall" == true ]]; then
        uninstall_package
        exit 0
    fi

    shell_name="$(detect_shell)"
    installer="$(pick_installer)"
    bin_dir="$(get_install_bin_dir "$installer")"

    log_info "Detected login shell: ${shell_name}"
    log_info "Expected CLI bin dir: ${bin_dir}"

    install_package "$installer"

    snippet="$(write_snippet "$shell_name" "$bin_dir")"
    rc_file="$(get_rc_file "$shell_name")"

    if [[ -n "$rc_file" ]]; then
        ensure_source_in_rc "$shell_name" "$snippet" "$rc_file" || true
    else
        log_warn "Skipping automatic shell config changes for shell '${shell_name}'"
    fi

    verify_installation "$bin_dir" || true
    print_manual_guidance "$shell_name" "$rc_file" "$snippet" "$bin_dir"

    echo ""
    log_ok "Installation complete"
}

main "$@"
